apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wizard.FULL_NAME" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wizard.FULL_NAME" . }}
  template:
    metadata:
      labels:
        app: {{ include "wizard.FULL_NAME" . }}
    spec:
      containers:
        - image: {{ include "wizard.IMAGE" . }}
          imagePullPolicy: Always
          name: {{ include "wizard.FULL_NAME" . }}
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: {{ include "backend.CONFIG_NAME" . }}
