name: Staging

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+' ]

jobs:
  build_wizard:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.lowercase }}
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/threefoldtech/threefold_connect_wizard/wizard
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Build and push
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:staging-${{ github.sha }},${{ env.IMAGE_NAME }}:staging-latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [ build_wizard ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting configs
        run: |
          echo "Creating folder"
          mkdir ${HOME}/.kube
          echo "Adding staging key"
          echo ${{ secrets.STAGING_KUBE_KEY }} | base64 --decode > ${HOME}/.kube/jimber-staging.key
          echo "Adding staging crt"
          echo ${{ secrets.STAGING_KUBE_CRT }} | base64 --decode > ${HOME}/.kube/jimber-staging.crt
          echo "Adding config"
          echo ${{ secrets.STAGING_KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat  ${HOME}/.kube/config
          cat  ${HOME}/.kube/jimber-staging.key
          cat  ${HOME}/.kube/config
      - name: Upgrade cluster
        run: |
          helm install staging-wizard helm_charts -f helm_charts/values/values-staging.yaml --set global.WIZARD_IMAGE=ghcr.io/threefoldtech/threefold_connect/wizard:staging-${{ github.sha }} --set global.DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}" --set global.DOCKER_PASSWORD="${{ secrets.DOCKER_TOKEN }}" -n jimber
